### ISSUE TITLE
Doesn't work in 3.2 editor

### ISSUE THREAD

**Issue by vlad0337187** [Calinou/godot-lod#5]
Hello.

- reproduced all from installation steps, but it didn't hide any objects.
- downloaded demo project, launched it, see no spheres were disappeared after looked from far distance

But when I launched game debug (triangle button) - than it showed me hiding.
Not sure where problem is.

Maybe some version mismatch (used latest master of this plugin, Godot v3.2.3 stable).
Does anybody has any hints on fixing this ?

Thanks.

**Comment by Calinou** [comment]
This LOD add-on does **not** run in the editor – this is by design to avoid making accidental changes to saved scenes. LOD is only effective in the running project.
